### PR TITLE
Update AvailablePluginsConfig.txt

### PR DESCRIPTION
**Pull request by uLow**

### CODE REVIEW

**Comment by zaafar** [comment]
It’s already there in the file.

**Comment by uLow** [comment]
Yeah, strange, cuz it was not showing up in my updater.

**Comment by zaafar** [comment]
https://github.com/Stridemann/PoeHUD_PluginsUpdater/blob/master/AvailablePluginsConfig.txt#L20

**Comment by zaafar** [comment]
Delete this file from your computer and re download it and then restart the poehud.

**Pull request closed without merging**
